# Firebase Functions Python Integration Test Suites Configuration
# Python SDK only supports V2 APIs - all tests deploy to functions-integration-tests-v2

defaults:
  projectId: functions-integration-tests-v2
  region: us-central1
  timeout: 540
  dependencies:
    firebase-admin: "^6.0.1"
    firebase-functions: "{{sdkTarball}}"
  devDependencies: {}

suites:
  # ============================================================================
  # V2 API Suites (Python SDK only supports V2 Firebase APIs)
  # ============================================================================

  # V2 Firestore triggers
  - name: v2_firestore
    description: "V2 Firestore trigger tests for Python"
    version: v2
    service: firestore
    functions:
      - name: firestoreOnDocumentCreated
        trigger: onDocumentCreated
        document: "tests/{testId}"
        collection: firestoreOnDocumentCreatedTests
      - name: firestoreOnDocumentDeleted
        trigger: onDocumentDeleted
        document: "tests/{testId}"
        collection: firestoreOnDocumentDeletedTests
      - name: firestoreOnDocumentUpdated
        trigger: onDocumentUpdated
        document: "tests/{testId}"
        collection: firestoreOnDocumentUpdatedTests
      - name: firestoreOnDocumentWritten
        trigger: onDocumentWritten
        document: "tests/{testId}"
        collection: firestoreOnDocumentWrittenTests

  # V2 Realtime Database triggers
  - name: v2_database
    description: "V2 Realtime Database trigger tests for Python"
    version: v2
    service: database
    functions:
      - name: databaseOnValueCreated
        trigger: onValueCreated
        path: "databaseCreatedTests/{testId}/start"
        collection: databaseCreatedTests
      - name: databaseOnValueDeleted
        trigger: onValueDeleted
        path: "databaseDeletedTests/{testId}/start"
        collection: databaseDeletedTests
      - name: databaseOnValueUpdated
        trigger: onValueUpdated
        path: "databaseUpdatedTests/{testId}/start"
        collection: databaseUpdatedTests
      - name: databaseOnValueWritten
        trigger: onValueWritten
        path: "databaseWrittenTests/{testId}/start"
        collection: databaseWrittenTests

  # V2 Pub/Sub triggers
  - name: v2_pubsub
    description: "V2 Pub/Sub trigger tests for Python"
    version: v2
    service: pubsub
    functions:
      - name: pubsubOnMessagePublished
        trigger: onMessagePublished
        topic: "firebase-functions-pubsub-v2"

  # V2 Storage triggers
  - name: v2_storage
    description: "V2 Storage trigger tests for Python"
    version: v2
    service: storage
    functions:
      - name: storageOnObjectArchived
        trigger: onObjectArchived
        bucket: "{{projectId}}.appspot.com"
      - name: storageOnObjectDeleted
        trigger: onObjectDeleted
        bucket: "{{projectId}}.appspot.com"
      - name: storageOnObjectFinalized
        trigger: onObjectFinalized
        bucket: "{{projectId}}.appspot.com"
      - name: storageOnObjectMetadataUpdated
        trigger: onObjectMetadataUpdated
        bucket: "{{projectId}}.appspot.com"

  # V2 Scheduler triggers
  - name: v2_scheduler
    description: "V2 Scheduled function tests for Python"
    version: v2
    service: scheduler
    functions:
      - name: schedulerOnSchedule
        trigger: onSchedule
        schedule: "every 1 minutes"

  # V2 Task Queue functions
  - name: v2_tasks
    description: "V2 Task Queue function tests for Python"
    version: v2
    service: tasks
    functions:
      - name: taskQueueOnEnqueue
        trigger: onTaskDispatched
        queueName: "v2-test-queue"

  # V2 Identity triggers
  - name: v2_identity
    description: "V2 Identity trigger tests for Python"
    version: v2
    service: identity
    functions:
      - name: identityBeforeUserCreated
        trigger: beforeUserCreated
      - name: identityBeforeUserSignedIn
        trigger: beforeUserSignedIn

  # V2 Eventarc triggers
  - name: v2_eventarc
    description: "V2 Eventarc trigger tests for Python"
    version: v2
    service: eventarc
    functions:
      - name: eventarcOnCustomEventPublished
        trigger: onCustomEventPublished
        eventType: "test.event.v1"

  # V2 Alerts triggers
  - name: v2_alerts
    description: "V2 Alerts trigger tests for Python"
    version: v2
    service: alerts
    functions:
      - name: alertsOnAlertPublished
        trigger: onAlertPublished
        alertType: "billing.planAutomatedUpdatePublished"

  # V2 Test Lab triggers
  - name: v2_testlab
    description: "V2 Test Lab trigger tests for Python"
    version: v2
    service: testlab
    functions:
      - name: testLabOnTestMatrixCompleted
        trigger: onTestMatrixCompleted

  # V2 Remote Config triggers
  - name: v2_remoteconfig
    description: "V2 Remote Config trigger tests for Python"
    version: v2
    service: remoteconfig
    functions:
      - name: remoteConfigOnConfigUpdated
        trigger: onConfigUpdated
