# Firebase Functions V1 Python Integration Test Suites Configuration
# This configuration is for Python functions and extends the base v1 configuration

defaults:
  projectId: functions-integration-tests
  region: us-central1
  timeout: 540
  dependencies:
    firebase-admin: "^6.0.1"
    firebase-functions: "{{sdkTarball}}"
  devDependencies: {}

suites:
  # Firestore triggers
  - name: v1_firestore
    description: "V1 Firestore trigger tests for Python"
    version: v1
    service: firestore
    functions:
      - name: firestoreDocumentOnCreateTests
        trigger: onCreate
        document: "tests/{testId}"
      - name: firestoreDocumentOnDeleteTests
        trigger: onDelete
        document: "tests/{testId}"
      - name: firestoreDocumentOnUpdateTests
        trigger: onUpdate
        document: "tests/{testId}"
      - name: firestoreDocumentOnWriteTests
        trigger: onWrite
        document: "tests/{testId}"

  # Realtime Database triggers
  - name: v1_database
    description: "V1 Realtime Database trigger tests for Python"
    version: v1
    service: database
    functions:
      - name: databaseRefOnCreateTests
        trigger: onCreate
        path: "dbTests/{testId}/start"
      - name: databaseRefOnDeleteTests
        trigger: onDelete
        path: "dbTests/{testId}/start"
      - name: databaseRefOnUpdateTests
        trigger: onUpdate
        path: "dbTests/{testId}/start"
      - name: databaseRefOnWriteTests
        trigger: onWrite
        path: "dbTests/{testId}/start"

  # Pub/Sub triggers
  - name: v1_pubsub
    description: "V1 Pub/Sub trigger tests for Python"
    version: v1
    service: pubsub
    functions:
      - name: pubsubOnPublish
        trigger: onPublish
        topic: "firebase-functions-pubsub-test"
      - name: pubsubOnPublishBinary
        trigger: onPublish
        topic: "firebase-functions-pubsub-test-binary"
      - name: pubsubOnMessagePublished
        trigger: onMessagePublished
        topic: "firebase-functions-pubsub-message"

  # Storage triggers
  - name: v1_storage
    description: "V1 Storage trigger tests for Python"
    version: v1
    service: storage
    functions:
      - name: storageOnObjectArchive
        trigger: onArchive
        bucket: "{{projectId}}.appspot.com"
      - name: storageOnObjectDelete
        trigger: onDelete
        bucket: "{{projectId}}.appspot.com"
      - name: storageOnObjectFinalize
        trigger: onFinalize
        bucket: "{{projectId}}.appspot.com"
      - name: storageOnObjectMetadataUpdate
        trigger: onMetadataUpdate
        bucket: "{{projectId}}.appspot.com"

  # Auth triggers
  - name: v1_auth_nonblocking
    description: "V1 Auth non-blocking trigger tests for Python"
    version: v1
    service: auth
    functions:
      - name: authOnCreate
        trigger: onCreate
      - name: authOnDelete
        trigger: onDelete

  # Auth blocking triggers
  - name: v1_auth_before_create
    description: "V1 Auth beforeCreate blocking trigger tests for Python"
    version: v1
    service: auth
    functions:
      - name: authBeforeCreate
        trigger: beforeCreate

  - name: v1_auth_before_signin
    description: "V1 Auth beforeSignIn blocking trigger tests for Python"
    version: v1
    service: auth
    functions:
      - name: authBeforeSignIn
        trigger: beforeSignIn

  # Remote Config triggers
  - name: v1_remoteconfig
    description: "V1 Remote Config trigger tests for Python"
    version: v1
    service: remoteconfig
    functions:
      - name: remoteConfigOnUpdate
        trigger: onUpdate

  # Test Lab triggers
  - name: v1_testlab
    description: "V1 Test Lab trigger tests for Python"
    version: v1
    service: testlab
    functions:
      - name: testLabOnComplete
        trigger: onComplete

  # Task Queue functions
  - name: v1_tasks
    description: "V1 Task Queue function tests for Python"
    version: v1
    service: tasks
    functions:
      - name: taskQueueFunction
        trigger: onDispatch
        queueName: "test-queue"